const projectCardData = [
  {
    id: 1,
    projectImg: "../src/assets/images/png/project-img.png",
    projectTitle: "project name",
    projectDetail:
      "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
    techStack: "Tech stack :",
    stackSkills: " HTML , JavaScript, SASS, React",
    liveIcon: "/src/assets/images/svg/live-link-icon.svg",
    livePreview: "Live Preview",
    viewCode: "View Code",
    smallGitIcon: "/src/assets/images/svg/github-small-icon.svg",
  },
  {
    id: 2,
    projectImg: "../src/assets/images/png/project-img.png",
    projectTitle: "project name",
    projectDetail:
      "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
    techStack: "Tech stack :",
    stackSkills: " HTML , JavaScript, SASS, React",
    liveIcon: "../src/assets/images/svg/live-link-icon.svg",
    livePreview: "Live Preview",
    viewCode: "View Code",
    smallGitIcon: "../src/assets/images/svg/github-small-icon.svg",
  },
  {
    id: 3,
    projectImg: "../src/assets/images/png/project-img.png",
    projectTitle: "project name",
    projectDetail:
      "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
    techStack: "Tech stack :",
    stackSkills: " HTML , JavaScript, SASS, React",
    liveIcon: "../src/assets/images/svg/live-link-icon.svg",
    livePreview: "Live Preview",
    viewCode: "View Code",
    smallGitIcon: "../src/assets/images/svg/github-small-icon.svg",
  },
  {
    id: 4,
    projectImg: "../src/assets/images/png/project-img.png",
    projectTitle: "project name",
    projectDetail:
      "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
    techStack: "Tech stack :",
    stackSkills: " HTML , JavaScript, SASS, React",
    liveIcon: "../src/assets/images/svg/live-link-icon.svg",
    livePreview: "Live Preview",
    viewCode: "View Code",
    smallGitIcon: "../src/assets/images/svg/github-small-icon.svg",
  },
  {
    id: 5,
    projectImg: "../src/assets/images/png/project-img.png",
    projectTitle: "project name",
    projectDetail:
      "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
    techStack: "Tech stack :",
    stackSkills: " HTML , JavaScript, SASS, React",
    liveIcon: "../src/assets/images/svg/live-link-icon.svg",
    livePreview: "Live Preview",
    viewCode: "View Code",
    smallGitIcon: "../src/assets/images/svg/github-small-icon.svg",
  },
  {
    id: 6,
    projectImg: "../src/assets/images/png/project-img.png",
    projectTitle: "project name",
    projectDetail:
      "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
    techStack: "Tech stack :",
    stackSkills: " HTML , JavaScript, SASS, React",
    liveIcon: "../src/assets/images/svg/live-link-icon.svg",
    livePreview: "Live Preview",
    viewCode: "View Code",
    smallGitIcon: "../src/assets/images/svg/github-small-icon.svg",
  },
];
export default projectCardData;
